// <auto-generated />
using System;
using DepositManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepositManager.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231026201324_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("DepositManager.Data.Bank", b =>
                {
                    b.Property<Guid>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BankId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            BankId = new Guid("58906590-74fb-425a-a85a-cdd47b729db7"),
                            BankName = "FNB"
                        },
                        new
                        {
                            BankId = new Guid("e8bd5276-91e0-42aa-bc2d-9518b7fa5adb"),
                            BankName = "ERIE"
                        },
                        new
                        {
                            BankId = new Guid("ae01dc8e-309a-4bc2-bfad-c9422b0c90ff"),
                            BankName = "Unassigned"
                        });
                });

            modelBuilder.Entity("DepositManager.Data.Check", b =>
                {
                    b.Property<Guid>("CheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DepositId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ReferenceNum")
                        .HasColumnType("REAL");

                    b.HasKey("CheckId");

                    b.HasIndex("DepositId");

                    b.ToTable("Check");

                    b.HasData(
                        new
                        {
                            CheckId = new Guid("b794d70a-6ede-40a8-94cb-178e2296827f"),
                            Amount = 15.25m,
                            CustomerName = "Free To Choose",
                            ReferenceNum = 1562.0
                        },
                        new
                        {
                            CheckId = new Guid("f3b86203-412f-401b-91b4-7089de5820f3"),
                            Amount = 2560.3m,
                            CustomerName = "Humes",
                            ReferenceNum = 125.0
                        });
                });

            modelBuilder.Entity("DepositManager.Data.Deposit", b =>
                {
                    b.Property<Guid>("DepositId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BankId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cash")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DepositStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("DepositId");

                    b.HasIndex("BankId");

                    b.ToTable("Deposit");
                });

            modelBuilder.Entity("DepositManager.Data.EmailSettings", b =>
                {
                    b.Property<Guid>("EmailSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Port")
                        .HasColumnType("REAL");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmailSettingsId");

                    b.ToTable("EmailSettings");

                    b.HasData(
                        new
                        {
                            EmailSettingsId = new Guid("05d14ecc-164c-4e15-8564-fbd46011251c"),
                            Hostname = "mail.example.com",
                            Password = "password",
                            Port = 587.0,
                            Recipient = "guy@example.com",
                            Username = "user@example.com"
                        });
                });

            modelBuilder.Entity("DepositManager.Data.Check", b =>
                {
                    b.HasOne("DepositManager.Data.Deposit", "Deposit")
                        .WithMany()
                        .HasForeignKey("DepositId");

                    b.Navigation("Deposit");
                });

            modelBuilder.Entity("DepositManager.Data.Deposit", b =>
                {
                    b.HasOne("DepositManager.Data.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });
#pragma warning restore 612, 618
        }
    }
}
