// <auto-generated />
using System;
using DepositManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepositManager.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240104152101_AddDepositTotalField")]
    partial class AddDepositTotalField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("DepositManager.Data.Bank", b =>
                {
                    b.Property<Guid>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BankId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            BankId = new Guid("46b0df0c-969b-4bb9-aa8f-4008a5f24abc"),
                            BankName = "FNB"
                        },
                        new
                        {
                            BankId = new Guid("ae53ad57-be68-4e3f-849e-abcff2cc24bc"),
                            BankName = "ERIE"
                        },
                        new
                        {
                            BankId = new Guid("c5866871-1b1e-4954-a99f-38277d50c0fa"),
                            BankName = "Unassigned"
                        });
                });

            modelBuilder.Entity("DepositManager.Data.Check", b =>
                {
                    b.Property<Guid>("CheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DepositId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ReferenceNum")
                        .HasColumnType("REAL");

                    b.HasKey("CheckId");

                    b.HasIndex("DepositId");

                    b.ToTable("Check");

                    b.HasData(
                        new
                        {
                            CheckId = new Guid("86b07ccd-7ea0-4a85-bbe6-1699df0d6a69"),
                            Amount = 15.25m,
                            CustomerName = "Free To Choose",
                            ReferenceNum = 1562.0
                        },
                        new
                        {
                            CheckId = new Guid("0b148340-2caf-415b-9f06-1afc28fc3466"),
                            Amount = 2560.3m,
                            CustomerName = "Humes",
                            ReferenceNum = 125.0
                        });
                });

            modelBuilder.Entity("DepositManager.Data.Deposit", b =>
                {
                    b.Property<Guid>("DepositId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BankId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cash")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DepositStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DepositTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("DepositId");

                    b.HasIndex("BankId");

                    b.ToTable("Deposit");
                });

            modelBuilder.Entity("DepositManager.Data.EmailSettings", b =>
                {
                    b.Property<Guid>("EmailSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmailSettingsId");

                    b.ToTable("EmailSettings");

                    b.HasData(
                        new
                        {
                            EmailSettingsId = new Guid("9e093be1-64c5-4920-b673-3d84e8961f0b"),
                            Hostname = "mail.example.com",
                            Password = "password",
                            Port = 587,
                            Recipient = "guy@example.com",
                            Username = "user@example.com"
                        });
                });

            modelBuilder.Entity("DepositManager.Data.Check", b =>
                {
                    b.HasOne("DepositManager.Data.Deposit", "Deposit")
                        .WithMany()
                        .HasForeignKey("DepositId");

                    b.Navigation("Deposit");
                });

            modelBuilder.Entity("DepositManager.Data.Deposit", b =>
                {
                    b.HasOne("DepositManager.Data.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });
#pragma warning restore 612, 618
        }
    }
}
